### ISSUE TITLE
Optimize LLM Prompts and Responses

### ISSUE THREAD

**Issue by srizvi** [and-voila/ai#42]
### Intro
Right now, we're using vanilla prompting methods for our crude prototype. We need to incorporate best-practices to improve the performance, security, and UX

### Reference
- https://wundergraph.com/blog/beyond_functions_seamlessly_build_ai_enhanced_apis_with_openai
- https://twitter.com/perborgen/status/1692168665570169236

## Task List

- [ ] Review reference documentation

- [ ] Integrate APIs to Wundergraph

- [ ] Define AI Agent(s) scope and tasks

- [ ] Add remaining tasks
